// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface Env {}
