/**
 * Regenerates the Instrument Serif *italic* subset.
 *
 * Fontsource ships the full latin italic — 21 kB for a face this site uses on
 * twelve characters, preloaded on every page. This asks Google Fonts for a cut
 * containing exactly those, which lands around 2 kB.
 *
 * Run it whenever italic text changes:
 *
 *     bun run fonts:italic
 *
 * Both generated files are committed, so a build never reaches the network.
 * `tests/unit/italic-subset.test.ts` fails if they fall behind the markup.
 *
 * The roman face is untouched and still comes from Fontsource — see the note in
 * scripts/lib/italic.ts for why it cannot be subset the same way.
 */

import { join } from 'node:path';

import { REPO_ROOT } from './lib/cjk';
import { collectItalicText, toCodePoint } from './lib/italic';

const OUT_DIR = join(REPO_ROOT, 'src/styles/fonts');
const WOFF2_NAME = 'instrument-serif-italic-subset.woff2';
const CSS_NAME = 'instrument-serif-italic-subset.css';

const FAMILY = 'Instrument Serif';
const WEIGHT = 400;

/** Chrome, so the API answers with woff2 rather than a truetype fallback. */
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const { characters, unresolved } = collectItalicText();

if (unresolved.length > 0) {
  console.error('Italic text this script cannot read statically:\n');
  for (const entry of unresolved) console.error(`  ${entry}`);
  console.error(
    '\nA subset built from the rest would silently drop whatever those render.\n' +
      'Either inline the text, or widen the subset by hand.',
  );
  process.exit(1);
}

if (characters.size === 0) {
  console.error('No italic text under src/ — nothing to subset.');
  process.exit(1);
}

const sorted = [...characters.keys()].sort();

console.warn(`Subsetting ${FAMILY} italic to ${sorted.length} characters:\n`);
for (const char of sorted) {
  console.warn(`  ${char}  ${toCodePoint(char).padEnd(8)} ${characters.get(char)!.join(', ')}`);
}

// `family` must keep its `+` separators literal, which searchParams would escape.
const query = new URLSearchParams({ text: sorted.join('') });
const cssHref = `https://fonts.googleapis.com/css2?family=${FAMILY.replace(/ /g, '+')}:ital,wght@1,${WEIGHT}&${query}`;

const cssResponse = await fetch(cssHref, { headers: { 'User-Agent': UA } });
if (!cssResponse.ok) {
  throw new Error(`Google Fonts returned ${cssResponse.status} for ${cssHref}`);
}

const stylesheet = await cssResponse.text();

// The request asked for `ital,wght@1,400`; if the API answered with the roman
// anyway, the site would ship an upright face under an italic @font-face.
if (!/font-style:\s*italic/.test(stylesheet)) {
  throw new Error(`Google Fonts did not return an italic face:\n${stylesheet}`);
}

const fontUrl = /url\((https:\/\/[^)]+)\)/.exec(stylesheet)?.[1];
if (!fontUrl) {
  throw new Error(`No font URL in the stylesheet Google Fonts returned:\n${stylesheet}`);
}

const fontResponse = await fetch(fontUrl, { headers: { 'User-Agent': UA } });
if (!fontResponse.ok) {
  throw new Error(`Font download returned ${fontResponse.status}`);
}

const font = new Uint8Array(await fontResponse.arrayBuffer());
// woff2 files open with the `wOF2` signature; anything else means we just saved
// an error page over the font.
const signature = new TextDecoder().decode(font.subarray(0, 4));
if (signature !== 'wOF2') {
  throw new Error(`Downloaded file is not woff2 (signature ${JSON.stringify(signature)})`);
}

await Bun.write(join(OUT_DIR, WOFF2_NAME), font);

await Bun.write(
  join(OUT_DIR, CSS_NAME),
  `/*
 * GENERATED by \`bun run fonts:italic\` (scripts/fetch-italic-font.ts) — do not edit.
 *
 * ${FAMILY} italic (SIL Open Font License 1.1), subset to the ${sorted.length} characters this
 * site sets in italic: ${sorted.join(' ')}
 *
 * The roman face is not subset — it renders publication titles and headings from
 * src/data/profile.ts, whose characters are not knowable from the markup.
 */

@font-face {
  font-family: '${FAMILY}';
  font-style: italic;
  font-weight: ${WEIGHT};
  font-display: swap;
  src: url('./${WOFF2_NAME}') format('woff2');
  unicode-range: ${sorted.map(toCodePoint).join(', ')};
}
`,
);

console.warn(`\nWrote src/styles/fonts/${WOFF2_NAME} (${(font.byteLength / 1024).toFixed(1)} kB)`);
console.warn(`Wrote src/styles/fonts/${CSS_NAME}`);
