/**
 * Regenerates the LXGW WenKai TC subset that sets the Chinese name.
 *
 * The full face is several megabytes because it carries every CJK ideograph, but
 * the site only ever shows a handful of them (`杨思祺`, and `中文` in the CV
 * menu). So this collects the CJK characters that actually get rendered and asks
 * Google Fonts for a subset containing exactly those — a few kilobytes, small
 * enough that Vite inlines it into the stylesheet as a data URI.
 *
 * Run it whenever Chinese text is added or removed:
 *
 *     bun run fonts:cjk
 *
 * Both generated files are committed, so a build never reaches the network.
 * `tests/unit/cjk-subset.test.ts` fails if they fall behind the site's copy.
 */

import { join } from 'node:path';

import { collectCjkCharacters, REPO_ROOT, toCodePointLabel } from './lib/cjk';

const OUT_DIR = join(REPO_ROOT, 'src/styles/fonts');
const WOFF2_NAME = 'lxgw-wenkai-tc-subset.woff2';
const CSS_NAME = 'lxgw-wenkai-tc-subset.css';

/**
 * The family as Google Fonts names it. Unlike the Noto Serif SC this replaced,
 * WenKai is not variable — Google Fonts serves it as three discrete weights
 * (300, 400, 700), and asking for a range answers 400 Bad Request. Only the
 * regular is fetched: the one place Chinese is set large is the hero
 * superscription, and a kai face at 700 is far too heavy for it.
 */
const FAMILY = 'LXGW WenKai TC';
const WEIGHT = 400;
const AXIS = `wght@${WEIGHT}`;

/** Chrome, so the API answers with woff2 rather than a truetype fallback. */
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const found = collectCjkCharacters();
if (found.size === 0) {
  console.error('No CJK characters under src/ — nothing to subset.');
  process.exit(1);
}

const characters = [...found.keys()];

console.warn(`Subsetting ${FAMILY} to ${characters.length} characters:\n`);
for (const [char, sources] of found) {
  console.warn(`  ${char}  ${toCodePointLabel(char).padEnd(8)} ${sources.join(', ')}`);
}

// `family` must keep its `+` separators literal, which searchParams would escape.
const query = new URLSearchParams({ text: characters.join('') });
const cssHref = `https://fonts.googleapis.com/css2?family=${FAMILY.replace(/ /g, '+')}:${AXIS}&${query}`;

const cssResponse = await fetch(cssHref, { headers: { 'User-Agent': UA } });
if (!cssResponse.ok) {
  throw new Error(`Google Fonts returned ${cssResponse.status} for ${cssHref}`);
}

const stylesheet = await cssResponse.text();
const fontUrl = stylesheet.match(/url\((https:\/\/[^)]+)\)/)?.[1];
if (!fontUrl) {
  throw new Error(`No font URL in the stylesheet Google Fonts returned:\n${stylesheet}`);
}

const fontResponse = await fetch(fontUrl, { headers: { 'User-Agent': UA } });
if (!fontResponse.ok) {
  throw new Error(`Font download returned ${fontResponse.status}`);
}

const font = new Uint8Array(await fontResponse.arrayBuffer());
// woff2 files open with the `wOF2` signature; anything else means we just saved
// an error page over the font.
const signature = new TextDecoder().decode(font.subarray(0, 4));
if (signature !== 'wOF2') {
  throw new Error(`Downloaded file is not woff2 (signature ${JSON.stringify(signature)})`);
}

await Bun.write(join(OUT_DIR, WOFF2_NAME), font);

const unicodeRange = characters.map(toCodePointLabel).join(', ');

await Bun.write(
  join(OUT_DIR, CSS_NAME),
  `/*
 * GENERATED by \`bun run fonts:cjk\` (scripts/fetch-cjk-font.ts) — do not edit.
 *
 * ${FAMILY} (SIL Open Font License 1.1), subset to the ${characters.length} characters this site
 * renders: ${characters.join(' ')}
 *
 * Small enough that Vite inlines it into the stylesheet, so the Chinese name
 * paints with the rest of the page instead of swapping in late.
 */

@font-face {
  font-family: '${FAMILY}';
  font-style: normal;
  font-weight: ${WEIGHT};
  font-display: swap;
  src: url('./${WOFF2_NAME}') format('woff2');
  unicode-range: ${unicodeRange};
}
`,
);

console.warn(`\nWrote src/styles/fonts/${WOFF2_NAME} (${(font.byteLength / 1024).toFixed(1)} kB)`);
console.warn(`Wrote src/styles/fonts/${CSS_NAME}`);
console.warn(`unicode-range: ${unicodeRange}`);
