name: Auto-merge Dependabot

on:
  pull_request:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number to merge'
        required: true
        type: number

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Merge PR
        run: |
          PR_NUMBER="${{ github.event.pull_request.number || github.event.inputs.pr_number }}"
          gh pr merge -R "${{ github.repository }}" --squash --auto "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_PR_TOKEN }}