name: Auto-merge Dependabot

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Merge PR
        run: |
          gh pr merge -R "${{ github.repository }}" --squash --auto "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_PR_TOKEN }}