name: Check Upstream Updates

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch:

jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for upstream changes
        id: check_upstream
        run: |
          UPSTREAM_URL="https://github.com/markhorn-dev/astro-sphere"
          git fetch origin main:upstream/main
          if ! git rev-parse --verify -q upstream/main; then
              echo "::set-output name=has_changes::false"
              exit 0
          fi
          if ! git rev-parse --verify -q main; then
              echo "::set-output name=has_changes::false"
              exit 0
          fi
          
          if [ -z "$(git log --oneline main..upstream/main)" ]; then
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi

      - name: Create issue if updates found
        if: steps.check_upstream.outputs.has_changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Upstream repository has updates',
              body: 'The upstream repository (https://github.com/markhorn-dev/astro-sphere) has updates. Please review and merge the changes manually.',
            });